# Generated by Django 5.1 on 2024-10-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0004_emailmergecontentmodel_extra_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='attachments', to='post_office.emailmodel', verbose_name='Emails'),
        ),
        migrations.AlterField(
            model_name='emailmergecontentmodel',
            name='extra_attachments',
            field=models.ManyToManyField(blank=True, related_name='extra_attachments', to='post_office.attachment', verbose_name='Extra Attachments'),
        ),
    ]
