# Generated by Django 5.1 on 2024-10-15 08:08

import post_office.models
import post_office.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0005_alter_attachment_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=post_office.settings.get_attachments_storage, upload_to=post_office.models.get_upload_path, verbose_name='File'),
        ),
    ]
