# Generated by Django 5.1 on 2024-09-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0012_dbmutex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailModel',
        ),
    ]
