# Generated by Django 5.1 on 2024-09-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0013_rename_email_emailmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailTemplate',
            new_name='EmailMergeModel',
        ),
    ]
