# Generated by Django 5.1 on 2024-09-04 13:29

import ckeditor.fields
import django.db.models.deletion
import post_office.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0014_rename_emailtemplate_emailmergemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, validators=[post_office.validators.validate_email_with_name], verbose_name='Email From')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Last Name')),
                ('preferred_language', models.CharField(blank=True, default='', help_text='Users preferred language', max_length=12, verbose_name='Language')),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailmergemodel',
            name='html_content',
        ),
        migrations.AddField(
            model_name='emailmergemodel',
            name='base_file',
            field=models.CharField(default='email/top.html', max_length=255, verbose_name='File name'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='to',
        ),
        migrations.AddField(
            model_name='emailmergemodel',
            name='extra_recipients',
            field=models.ManyToManyField(blank=True, help_text='extra bcc recipients', null=True, to='post_office.emailaddress'),
        ),
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_name', models.CharField(max_length=63, verbose_name='Placeholder name')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='post_office.emailmergemodel')),
            ],
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='bcc',
            field=models.ManyToManyField(related_name='bcc_emails', to='post_office.emailaddress'),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='cc',
            field=models.ManyToManyField(related_name='cc_emails', to='post_office.emailaddress'),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='to',
            field=models.ManyToManyField(related_name='to_emails', to='post_office.emailaddress'),
        ),
    ]
