# Generated by Django 5.1 on 2024-09-02 11:49

import post_office.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0014_rename_emailtemplate_emailmergemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('email', models.CharField(db_index=True, max_length=254, primary_key=True, serialize=False, validators=[post_office.validators.validate_email_with_name], verbose_name='Email From')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Last Name')),
                ('preferred_language', models.CharField(blank=True, default='', help_text='Users preferred language', max_length=12, verbose_name='Language')),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
