# Generated by Django 5.1 on 2024-09-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0015_emailaddress_remove_emailmergemodel_html_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmodel',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='to',
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('to', 'To'), ('cc', 'Cc'), ('bcc', 'Bcc')], default='to', max_length=12)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_office.emailaddress')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_office.emailmodel')),
            ],
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='recipients',
            field=models.ManyToManyField(related_name='to_emails', through='post_office.Recipient', to='post_office.emailaddress'),
        ),
    ]
