# Generated by Django 5.1 on 2024-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0015_emailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmodel',
            name='bcc',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='emailmodel',
            name='to',
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='bcc',
            field=models.ManyToManyField(related_name='bcc_emails', to='post_office.emailaddress'),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='cc',
            field=models.ManyToManyField(related_name='cc_emails', to='post_office.emailaddress'),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='to',
            field=models.ManyToManyField(related_name='to_emails', to='post_office.emailaddress'),
        ),
    ]
