# Generated by Django 5.1 on 2024-09-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0016_remove_emailmodel_bcc_remove_emailmodel_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmergemodel',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, to='post_office.emailaddress'),
        ),
    ]
