# Generated by Django 5.1 on 2024-09-03 08:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0017_emailmergemodel_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmergemodel',
            name='recipients',
        ),
        migrations.AddField(
            model_name='emailmergemodel',
            name='extra_recipients',
            field=models.ManyToManyField(blank=True, help_text='extra bcc recipients', null=True, to='post_office.emailaddress'),
        ),
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_name', models.CharField(max_length=63, verbose_name='Placeholder name')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='post_office.emailmergemodel')),
            ],
        ),
    ]
