# Generated by Django 5.1 on 2024-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0018_remove_emailmergemodel_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmergemodel',
            name='base_file',
            field=models.CharField(default='email/placeholders.html', max_length=255, verbose_name='File name'),
            preserve_default=False,
        ),
    ]
