# Generated by Django 5.1 on 2024-09-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0019_emailmergemodel_base_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmergemodel',
            name='html_content',
        ),
    ]
