# Generated by Django 5.1 on 2024-09-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0020_emailcontent_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcontent',
            old_name='template',
            new_name='emailmerge',
        ),
        migrations.AddConstraint(
            model_name='emailcontent',
            constraint=models.UniqueConstraint(fields=('emailmerge', 'placeholder_name', 'language'), name='unique_placeholder'),
        ),
    ]
