# Generated by Django 5.1 on 2024-09-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0021_rename_template_emailcontent_emailmerge_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailmergemodel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='emailmergemodel',
            constraint=models.UniqueConstraint(fields=('name', 'language', 'default_template'), name='unique_emailmerge'),
        ),
    ]
