# Generated by Django 5.1 on 2024-09-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0024_rename_emailcontent_placeholdercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeholdercontent',
            name='base_file',
            field=models.CharField(default='email/top.html', max_length=255, verbose_name='File name'),
            preserve_default=False,
        ),
    ]
