# Generated by Django 5.1 on 2024-09-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0025_placeholdercontent_base_file'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='placeholdercontent',
            name='unique_placeholder',
        ),
        migrations.AddConstraint(
            model_name='placeholdercontent',
            constraint=models.UniqueConstraint(fields=('emailmerge', 'placeholder_name', 'language', 'base_file'), name='unique_placeholder'),
        ),
    ]
