# Generated by Django 5.1 on 2024-09-24 11:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0026_remove_placeholdercontent_unique_placeholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeholdercontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
    ]
