[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py39"
exclude=[
    'demoapp',
    'post_office/tests'
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
