# Generated by Django 5.1 on 2024-10-15 08:08

import sendmail.models
import sendmail.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0005_alter_attachment_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=sendmail.settings.get_attachments_storage, upload_to=sendmail.models.get_upload_path, verbose_name='File'),
        ),
    ]
